import { useState } from 'react'
import { listRecords } from '../records/records.ts'
import { secondsPerBox, topCombos, topFlavors } from './stats.ts'
import { flavorOrPlaceholder } from '../../data/flavors.ts'
import type { BoxRecord } from '../../domain/types.ts'

interface StatsScreenProps { demoRecords?: BoxRecord[] }
export function StatsScreen({ demoRecords }: StatsScreenProps) { const isDemo = demoRecords !== undefined; const [stored, setStored] = useState(() => listRecords()); const records = isDemo ? demoRecords : stored; const flavors = topFlavors(records); const combos = topCombos(records); const maxFlavorCount = flavors[0]?.count ?? 1
  // The number the prompt scores: seconds per box, measured. Median, not mean, so one
  // box left open through a rush can't drag it; range and n shown so a median over two
  // boxes can't read as a result.
  const pace = secondsPerBox(records)
  const slowest = Math.max(1, ...pace.map((p) => p.medianSeconds ?? 0))
  return <section aria-labelledby="stats-heading" className="dashboard-screen"><div className="page-heading"><div><p className="eyebrow">Flavor intelligence</p><h2 id="stats-heading">Your chocolate pulse <span>{records.length}</span></h2><p>Patterns from the boxes you’ve built so far.</p></div><button type="button" className="button button-light" onClick={() => setStored(listRecords())} disabled={isDemo}>↻ Refresh</button></div><div className="insight-card pace-card"><div className="card-heading"><div><p className="eyebrow">Measured, not guessed</p><h3>Seconds per box</h3></div><span className="card-spark">⏱</span></div><ul className="stats-bars">{pace.map((p) => <li key={p.size}><span className="rank">{p.size}</span><span className="stats-bar-label">{p.size}-piece</span>{p.medianSeconds === null ? <span className="muted-copy pace-empty">no boxes yet</span> : <span className="stats-bar-track"><span className="stats-bar-fill" style={{ width: `${(p.medianSeconds / slowest) * 100}%` }} /></span>}<strong className="stats-bar-count">{p.medianSeconds === null ? '—' : `${p.medianSeconds}s`}</strong></li>)}</ul><p className="muted-copy pace-note">{pace.some((p) => p.count > 0) ? pace.filter((p) => p.count > 0).map((p) => `${p.size}-piece: ${p.fastestSeconds}–${p.slowestSeconds}s over ${p.count}`).join(' · ') : 'Save a box and its time lands here.'}</p></div><div className="stats-grid"><div className="insight-card"><div className="card-heading"><div><p className="eyebrow">Top picks</p><h3>Most-picked flavors</h3></div><span className="card-spark">↗</span></div>{flavors.length === 0 ? <p className="muted-copy">No boxes saved yet.</p> : <ul className="stats-bars">{flavors.map(({ flavorId, count }, index) => <li key={flavorId}><span className="rank">0{index + 1}</span><span className="stats-bar-label">{flavorOrPlaceholder(flavorId).name}</span><span className="stats-bar-track"><span className="stats-bar-fill" style={{ width: `${(count / maxFlavorCount) * 100}%` }} /></span><strong className="stats-bar-count">{count}</strong></li>)}</ul>}</div><div className="insight-card combo-card"><div className="card-heading"><div><p className="eyebrow">Repeat behavior</p><h3>Customer favorites</h3></div><span className="card-spark">✦</span></div>{combos.length === 0 ? <p className="muted-copy">Not enough multi-flavor boxes yet.</p> : <ol className="stats-combos">{combos.map((combo, index) => <li key={combo.flavorIds.join('|')}><span>{index + 1}</span><div><strong>{combo.flavorIds.map((id) => flavorOrPlaceholder(id).name).join(' + ')}</strong><small>{combo.count} box{combo.count === 1 ? '' : 'es'}</small></div></li>)}</ol>}</div></div></section>
}
