import { useState } from 'react'
import { listRecords } from '../records/records.ts'
import { topCombos, topFlavors } from './stats.ts'
import { getFlavor } from '../../data/flavors.ts'
import type { BoxRecord } from '../../domain/types.ts'

interface StatsScreenProps { demoRecords?: BoxRecord[] }
export function StatsScreen({ demoRecords }: StatsScreenProps) { const isDemo = demoRecords !== undefined; const [stored, setStored] = useState(() => listRecords()); const records = isDemo ? demoRecords : stored; const flavors = topFlavors(records); const combos = topCombos(records); const maxFlavorCount = flavors[0]?.count ?? 1
  return <section aria-labelledby="stats-heading" className="dashboard-screen"><div className="page-heading"><div><p className="eyebrow">Flavor intelligence</p><h2 id="stats-heading">Your chocolate pulse <span>{records.length}</span></h2><p>Patterns from the boxes you’ve built so far.</p></div><button type="button" className="button button-light" onClick={() => setStored(listRecords())} disabled={isDemo}>↻ Refresh</button></div><div className="stats-grid"><div className="insight-card"><div className="card-heading"><div><p className="eyebrow">Top picks</p><h3>Most-picked flavors</h3></div><span className="card-spark">↗</span></div>{flavors.length === 0 ? <p className="muted-copy">No boxes saved yet.</p> : <ul className="stats-bars">{flavors.map(({ flavorId, count }, index) => <li key={flavorId}><span className="rank">0{index + 1}</span><span className="stats-bar-label">{getFlavor(flavorId).name}</span><span className="stats-bar-track"><span className="stats-bar-fill" style={{ width: `${(count / maxFlavorCount) * 100}%` }} /></span><strong className="stats-bar-count">{count}</strong></li>)}</ul>}</div><div className="insight-card combo-card"><div className="card-heading"><div><p className="eyebrow">Repeat behavior</p><h3>Customer favorites</h3></div><span className="card-spark">✦</span></div>{combos.length === 0 ? <p className="muted-copy">Not enough multi-flavor boxes yet.</p> : <ol className="stats-combos">{combos.map((combo, index) => <li key={combo.flavorIds.join('|')}><span>{index + 1}</span><div><strong>{combo.flavorIds.map((id) => getFlavor(id).name).join(' + ')}</strong><small>{combo.count} box{combo.count === 1 ? '' : 'es'}</small></div></li>)}</ol>}</div></div></section>
}
