import { useState } from 'react'
import { clearRecords, listRecords } from './records.ts'
import { toCSV, toJSON } from './csv.ts'
import { getFlavor } from '../../data/flavors.ts'
import type { BoxRecord } from '../../domain/types.ts'

function download(filename: string, content: string, mime: string) { const blob = new Blob([content], { type: mime }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url) }
interface RecordsScreenProps { demoRecords?: BoxRecord[]; onChange?: () => void }

export function RecordsScreen({ demoRecords, onChange }: RecordsScreenProps) { const isDemo = demoRecords !== undefined; const [stored, setStored] = useState(() => listRecords()); const records = isDemo ? demoRecords : stored; function refresh() { setStored(listRecords()) }; function handleClear() { if (!window.confirm('Clear all saved box records? This cannot be undone.')) return; clearRecords(); refresh(); onChange?.() }
  return <section aria-labelledby="records-heading" className="dashboard-screen"><div className="page-heading"><div><p className="eyebrow">Operations log</p><h2 id="records-heading">Saved boxes ({records.length}){isDemo ? ' · demo' : ''}</h2><p>Every box tells you a little more about what customers love.</p></div><span className="mode-badge">{isDemo ? 'Demo data' : 'Live records'}</span></div><div className="records-actions"><button type="button" className="button button-light" onClick={refresh} disabled={isDemo}>↻ Refresh</button><button type="button" className="button button-light" onClick={() => download('box-records.csv', toCSV(records), 'text/csv')} disabled={records.length === 0}>↓ Export CSV</button><button type="button" className="button button-light" onClick={() => download('box-records.json', toJSON(records), 'application/json')} disabled={records.length === 0}>↓ Export JSON</button><button type="button" className="button button-quiet danger-button" onClick={handleClear} disabled={isDemo || stored.length === 0}>Clear all</button></div>{records.length === 0 ? <div className="empty-state"><span>✦</span><h3>No boxes saved yet.</h3><p>Start assembling a box to see your counter history here.</p></div> : <ul className="records-list">{records.map((r) => <li key={r.id}><div className="record-icon">{r.size}</div><div className="record-main"><strong>{r.size}-piece box {r.demo && <span className="record-demo">Demo</span>}</strong><p>{r.pieces.map((p) => `${getFlavor(p.flavorId).name} ×${p.count}`).join(' · ')}</p></div><div className="record-meta"><strong>{(r.durationMs / 1000).toFixed(1)}s</strong><span>{r.undoCount > 0 ? `${r.undoCount} undo${r.undoCount === 1 ? '' : 's'}` : 'No undos'}</span></div></li>)}</ul>}</section>
}
