// Typed view over src/data/flavors.json, regenerated by scripts/fetch-flavors.mjs
// from Cocoa Dolce's public store feed. See that script for how the data is derived.

import type { Flavor } from '../domain/types.ts'
import raw from './flavors.json'

// The JSON file has no way to express the ChocolateType union, so it's typed as
// `string | null` on disk; scripts/fetch-flavors.mjs only ever writes valid values.
export const FLAVORS: readonly Flavor[] = raw.flavors as Flavor[]
export const FLAVORS_FETCHED_AT: string = raw.fetchedAt

const byId = new Map(FLAVORS.map((f) => [f.id, f]))

/** Looks up a flavor by id. Throws if the id isn't in the catalog, since a box record
 * referencing an unknown flavor is a data bug, not a normal runtime case. */
export function getFlavor(id: string): Flavor {
  const flavor = byId.get(id)
  if (!flavor) throw new Error(`Unknown flavor id: ${id}`)
  return flavor
}
